function about(title)

load secfile                           

ScreenSize=get(0,'ScreenSize');
FigWidth=300;FigHeight=200;
FigPos(1)=(ScreenSize(3)-FigWidth)/2;
FigPos(2)=(ScreenSize(4)-FigHeight)/2;
FigPos(3)=FigWidth;
FigPos(4)=FigHeight;


a = figure(...
    'Color',[0.8 0.8 0.8], ...
    'Colormap',mat0, ...
    'Position',FigPos, ...
    'Resize', 'off', ...
    'MenuBar','none', ...
    'NumberTitle','off', ...
    'Name','About TSTOOL', ...
    'Tag','sinputdlg');

d=uicontrol('Parent',a,...
         'Style','Text',...
	 'Background', [0.8 0.8 0.8], ...
         'Position',[10 35 280 120], ...
         'String',{title,'','Drittes Physikalisches Institut','Georg-August-Universität Göttingen', ...
	 '','http://www.physik3.gwdg.de/tstool',''});

d=uicontrol('Parent',a,'Style','pushbutton','Position',[125 5 50 25],...
    'String','Ok',...
    'Callback','uiresume');

uiwait;
close(gcf);
