function out = NL_DVV(x, m, numDVs, nd, Ntv, numSurr, randomSeed)
% NL_DVV   How well nearby delay vectors predict the next value, compared with surrogates.
%
% Delay vector variance (DVV) method for real and complex signals, using the
% original code of the DVV toolbox (below). A delay vector is a run of m
% consecutive values and its target is the value that follows. For each of
% numDVs randomly chosen reference vectors, the variance of the targets of all
% delay vectors within a distance rd of the reference is found (only if at
% least 30 vectors lie within rd). The mean of these variances over the
% references, divided by the variance of the series, is the target variance;
% it is computed at Ntv values of rd that span the mean distance between delay
% vectors plus or minus nd standard deviations. The same curve is found for
% numSurr iterative amplitude-adjusted Fourier transform (IAAFT) surrogates,
% and the outputs summarize the data curve and its difference from the mean
% surrogate curve.
%
% ---USAGE:
% outputStats = NL_DVV(x, m, numDVs, nd, Ntv, numSurr, randomSeed)
%
% ---INPUTS:
% x, original real-valued or complex time series
% m, delay embedding dimension (default: 3)
% numDVs, number of reference delay vectors to consider (default: 100)
% nd, span over which to perform DVV, in standard deviations of the distances
%     between delay vectors (default: 2)
% Ntv, number of points on the horizontal (distance) axis (default: 25*nd)
% numSurr, number of surrogates to compare to (default: 10)
% randomSeed, how to control the random seed for reproducibility
%
% ---OUTPUTS: statistics of the curve of target variance against standardized
% distance (the "data curve", using only distances at which it is defined):
% trend, slope of a linear fit to the data curve
% max, min, mean: maximum, minimum and mean of the data curve
% meanDiff, stdDiff: mean and standard deviation of the successive differences
%           of the data curve
% trendDiff, slope of a linear fit to the successive differences
% rmsDiffSurr, meanDiffSurr: root-mean-square and mean difference between the
%           data curve and the mean surrogate curve
% numZeroCrossings, number of sign changes of that difference
% trendSurr, slope of a linear fit to the mean surrogate curve
% meanDiffTrendSurr, trendSurr minus trend
% meanNormCDF, mean over distances of the Gaussian cumulative probability of the
%           data curve value, given the mean and standard deviation across the
%           surrogates
% dataSurrCorr, trendDataSurr: correlation between the data curve and the mean
%           surrogate curve, and slope of the mean surrogate curve against the
%           data curve (computed but not registered as features; see below)
%
% ---NOTES:
% Surrogates are generated by Toolboxes/DVV_Toolbox/DVV_surrogate.m, which
% hctsa patches in-place (real-valued branch only) to fix a performance
% issue: the original always ran the full 1000-iteration
% IAAFT budget for every surrogate (its convergence check essentially never
% triggers -- MSE oscillates rather than converging, a known property of
% vanilla IAAFT), accounting for ~85% of this operation's runtime for no
% benefit. See DVV_surrogate.m's own docstring for details of the fix.
%
% Whether this operation actually detects real structure was checked directly:
% on chaotic generators (logistic map, Henon map,
% Lorenz) vs linear-stochastic controls (AR(2), white noise), several
% surrogate-comparison fields (rmsDiffSurr, meanDiffSurr, meanDiffTrendSurr,
% meanNormCDF, numZeroCrossings, trendSurr) separate the two groups cleanly
% (p<0.002, n=15/group) with exactly the sign the method predicts (real
% data sits below the surrogate ensemble for genuinely deterministic
% systems). Not simply redundant with CO_TC3/CO_trev/SD_Surrogates/
% SD_SurrogateTest either (|r| mostly <0.5 on two collections of real-world series).
%
% Two fields dropped from registration (out.trendDataSurr and
% out.dataSurrCorr are still computed here but no longer exposed as
% features -- removed from INP_ops_hctsa.txt only):
% - trendDataSurr: showed no discrimination at all in the chaotic-vs-linear
%   test (p=0.72).
% - dataSurrCorr: fundamentally ill-conditioned, not just noisy. It's
%   Pearson correlation between the real and surrogate-mean DVV curves
%   across Ntv points; whenever either curve is close to flat (always true
%   for linear/noise data by design, and often true for the 10-surrogate
%   mean curve even for genuinely chaotic data, just by which surrogates
%   got drawn), the correlation becomes numerically unstable and can flip
%   sign for the SAME underlying generator (verified directly: 10 Henon
%   realizations gave dataSurrCorr in [-0.29, 0.91] depending only on
%   whether that realization's surrogate-mean curve happened to be flat).
%
% A Delay Vector Variance (DVV) toolbox for MATLAB
% (c) Copyright Danilo P. Mandic 2008
% http://www.commsp.ee.ic.ac.uk/~mandic/dvv.htm
% http://www.commsp.ee.ic.ac.uk/~mandic/dvv/papers/dvv_proj.pdf
%
% ------------------------------------------------------------------------------
% Modified by Ben Fulcher, 2015-05-13, for use in hctsa.
% If you use this code for your research, please cite the following two papers:
%
% (1) B.D. Fulcher and N.S. Jones, "hctsa: A Computational Framework for Automated
% Time-Series Phenotyping Using Massive Feature Extraction, Cell Systems 5: 527 (2017).
% DOI: 10.1016/j.cels.2017.10.001
%
% (2) B.D. Fulcher, M.A. Little, N.S. Jones, "Highly comparative time-series
% analysis: the empirical structure of time series and their methods",
% J. Roy. Soc. Interface 10(83) 20130048 (2013).
% DOI: 10.1098/rsif.2013.0048
% ------------------------------------------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   This program is free software; you can redistribute it and/or modify it
%   under the terms of the GNU General Public License as published by the Free
%   Software Foundation; either version 2 of the License, or (at your option)
%   any later version.
%
%   This program is distributed in the hope that it will be useful, but WITHOUT
%   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
%   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
%   more details.
%
%   You can obtain a copy of the GNU General Public License from
%   http://www.gnu.org/copyleft/gpl.html or by writing to Free Software
%   Foundation, Inc.,675 Mass Ave, Cambridge, MA 02139, USA.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Plot output plot:
doPlot = false;

% Talk to me:
beVocal = false;

% ------------------------------------------------------------------------------
% Check inputs:
% ------------------------------------------------------------------------------
if nargin < 1
	error('Not enough input arguments');
end
if nargin < 2 || isempty(m)
	m = 3;
end
if nargin < 3 || isempty(numDVs)
	numDVs = 100;
end
if nargin < 4 || isempty(nd)
	nd = 2.0;
end
if nargin < 5 || isempty(Ntv)
	Ntv = 25 * nd;
end
if nargin < 6 || isempty(numSurr)
	numSurr = 10;
end
if nargin < 7
	randomSeed = [];
end

% ------------------------------------------------------------------------------
% Preliminaries
% ------------------------------------------------------------------------------
BF_ResetSeed(randomSeed); % Reset the random seed if specified

% DVV_dvv draws numDVs reference delay vectors without replacement from the
% N - m available, so a short series cannot supply them (data-dependent):
if length(x) - m < numDVs
	warning('Time series (N = %u) too short to draw %u reference delay vectors at m = %u', length(x), numDVs, m);
	out = NaN; return
end

% ------------------------------------------------------------------------------
% Run DVV on input data:
% ------------------------------------------------------------------------------
if beVocal, fprintf(1, 'dvv on data...'); end
dvv_data = DVV_dvv(x, m, numDVs, nd, Ntv);
if beVocal, fprintf(1, ' Done.\n'); end

% ------------------------------------------------------------------------------
% Generate surrogate data and run DVV on the surrogates
% ------------------------------------------------------------------------------
if beVocal, fprintf(1, 'Generating %u surrogates...', numSurr); end
x_surr = DVV_surrogate(x, numSurr);
if beVocal, fprintf(1, ' Done.\n'); end

if beVocal, fprintf(1, 'Computing dvv for surrogates...'); end
dvv_surr = zeros(Ntv, 2, numSurr);
for i = 1:numSurr
	dvv_surr(:, :, i) = DVV_dvv(x_surr(:, i), m, numDVs, nd, Ntv);
end
mean_dvv_surr = mean(dvv_surr, 3);
if beVocal, fprintf(1, ' Done.\n'); end

% ------------------------------------------------------------------------------
% Plotting:
% ------------------------------------------------------------------------------
if doPlot
	f = figure('color', 'w'); box('on');
	subplot(1, 2, 1); hold on
	plot(dvv_data(:, 1), dvv_data(:, 2), '.-k')
	plot(mean_dvv_surr(:, 1), mean_dvv_surr(:, 2), '.-r')
	legend({'data', 'surrogate mean'})
	xlabel('~distance')
	ylabel('target variance')

	% DVV scatter plot
	subplot(1, 2, 2); hold on
	biSector = 0:0.5:1;
	plot(biSector, biSector, ':k'); axis([0 1 0 1]);
	title('DVV Scatter Plot'); xlabel('Original'); ylabel('Surrogates'); grid on; hold on
	errorbar(dvv_data(:, 2), mean_dvv_surr(:, 2), std(dvv_surr(:, 2, :), [], 3));
end

% ------------------------------------------------------------------------------
% Quantify and output patterns in the distance versus target variance data
% (for both real data and surrogates)
% ------------------------------------------------------------------------------

dvv_data_notNaN = dvv_data(~isnan(dvv_data(:, 2)), :);

% Is there a trend in the data?
out.trend = GiveMeGradient(dvv_data_notNaN(:, 1), dvv_data_notNaN(:, 2));

% What's the distribution of values like
out.max = max(dvv_data_notNaN(:, 2));
out.min = min(dvv_data_notNaN(:, 2));
out.mean = mean(dvv_data_notNaN(:, 2));

% Analysis of successive differences in the real data:
% (assume that NaNs occur in contiguous block at the start; for low distances)
out.meanDiff = mean(diff(dvv_data_notNaN(:, 2)));
out.stdDiff = std(diff(dvv_data_notNaN(:, 2)));
out.trendDiff = GiveMeGradient(dvv_data_notNaN(1:end - 1, 1), diff(dvv_data_notNaN(:, 2)));

% Are there large differences between real and surrogate data?
notNaN = ~isnan(dvv_data(:, 2)) & ~isnan(mean_dvv_surr(:, 2));
out.rmsDiffSurr = sqrt(mean((dvv_data(notNaN, 2) - mean_dvv_surr(notNaN, 2)).^2));
out.meanDiffSurr = mean(dvv_data(notNaN, 2) - mean_dvv_surr(notNaN, 2));

% What's the correlation between the original and surrogate DVV values
out.dataSurrCorr = corr(dvv_data(notNaN, 2), mean_dvv_surr(notNaN, 2));

% Trend in DVV scatter plot
out.trendDataSurr = GiveMeGradient(dvv_data(notNaN, 2), mean_dvv_surr(notNaN, 2));

% Number of zero crossings of data/surrogate data curve
out.numZeroCrossings = sum(BF_SignChange(dvv_data(notNaN, 2) - mean_dvv_surr(notNaN, 2)));

% Difference in trend between real and surrogate:
out.trendSurr = GiveMeGradient(mean_dvv_surr(notNaN, 1), mean_dvv_surr(notNaN, 2));
out.meanDiffTrendSurr = out.trendSurr - out.trend;

% Mean probability assuming Gaussian distribution of test stat for surrogates:
probs = zeros(sum(notNaN), 1);
fnotNaN = find(notNaN);
for i = 1:sum(notNaN)
	probs(i) = normcdf(dvv_data(fnotNaN(i), 2), mean(dvv_surr(fnotNaN(i), 2, :)), std(dvv_surr(fnotNaN(i), 2, :)));
end
out.meanNormCDF = mean(probs);

% ------------------------------------------------------------------------------
function m = GiveMeGradient(xData, yData)
	if size(xData, 1) ~= size(yData, 1);
		yData = yData';
	end
	p = polyfit(xData, yData, 1);
	m = p(1);
end
% ------------------------------------------------------------------------------

end
