function out = SD_Surrogates(y, tau, nsurr, surrMethod, surrfn, randomSeed)
% SD_Surrogates   Surrogate data test of a nonlinear statistic, tc3 or trev.
%
% Generates surrogate time series and tests them against the original time series
% according to a test statistic: T_{C3} (CO_TC3.m) or T_{rev} (CO_trev.m), both
% reimplementations of the expressions originally used by the TSTOOL package's tc3/trev
% functions. Surrogates are generated by SD_MakeSurrogates.m rather than TSTOOL (this
% operation no longer depends on TSTOOL). The statistic is computed on the series and on
% each surrogate, and the outputs describe where the series' value lies in the distribution
% of the surrogates' values (a Gaussian fit to them, their median and interquartile range,
% and a kernel-smoothed density, see BF_KSDensity).
%
% ---INPUTS:
% y, the input time series
% tau, the time lag used in the test statistic (an integer, or a string that sets it from
%      the series: 'ac' for the first zero-crossing of the autocorrelation function,
%      'ac1e' for the floor of its first 1/e crossing, or 'mi' for the smaller of the
%      first minimum of the Kraskov automutual information and the 'ac1e' delay; see
%      BF_GetTau; default: 1). The delay is set once, from the original series, and
%      used for the series and all its surrogates. For 'tc3' the statistic is
%      <x_n x_{n-tau} x_{n-2tau}> / |<x_n x_{n-tau}>|^(3/2); for 'trev' it is
%      <d^3> / <d^2>^(3/2) for the increments d = x_{n+tau} - x_n.
% nsurr, the number of surrogates to generate (default: 50)
% surrMethod, the method of generating surrogates (default: 1):
%               (i) 1: randomizes phases of Fourier spectrum (SD_MakeSurrogates 'RP')
%               (ii) 2: Theiler's algorithm II (SD_MakeSurrogates 'AAFT')
%               (iii) 3: permutes samples randomly (SD_MakeSurrogates 'RandPerm')
% surrfn, the surrogate statistic to evaluate on all surrogates, either 'tc3' or 'trev'
%         (default: 'tc3')
% randomSeed, whether (and how) to reset the random seed, using BF_ResetSeed
%
% ---OUTPUTS: (s is the value of the statistic on the series; the surrogates' values have
% mean muhat, standard deviation sigmahat, median and interquartile range iqrsurr)
% meansurr, the mean of the statistic over the surrogates
% meannumsurr, the mean over the surrogates of the statistic's numerator: for 'tc3',
%         <x_n x_{n-tau} x_{n-2tau}>; for 'trev', <d^3>. Unlike meansurr it has no
%         denominator, so it is not dominated by the few surrogates whose denominator is
%         near zero (for 'tc3', |<x_n x_{n-tau}>| is small whenever the surrogate's
%         lag-tau autocorrelation is). It is the mean third-order moment of the null
%         ensemble: for AAFT surrogates (surrMethod = 2) it measures how much
%         <x_n x_{n-tau} x_{n-2tau}> a static monotone transform of a linear Gaussian
%         process with this series' distribution and autocorrelation produces. For 'trev'
%         and for random-phase surrogates (surrMethod = 1) its expectation is near zero for
%         every series (the null processes are time-reversible, and random phases cancel
%         third-order moments of a zero-mean series); for permuted surrogates
%         (surrMethod = 3) it depends only on the series' distribution.
% stdsurr, the standard deviation of the statistic over the surrogates
% normpatponmax, the Gaussian density N(muhat, sigmahat) at s relative to its peak value
% stdfrommean, |s - muhat|/sigmahat
% zsigned, (s - muhat)/sigmahat: the z-score of the series' statistic against the
%         surrogates, keeping its sign (whether the series has more or less of the
%         statistic than the null ensemble); NaN if sigmahat is at the rounding level of
%         the surrogates' values (sigmahat <= 1e-10*max|value|), where no meaningful
%         z-score exists
% ztestp, the p-value of a z-test of s against N(muhat, sigmahat)
% iqrsfrommedian, |s - median|/iqrsurr (NaN if iqrsurr = 0)
% kspminfromext, the smaller of the kernel-density probabilities of a value below and above
%         s (0 if s lies above the density grid)
% ksphereonmax, the kernel density at s relative to the peak of N(muhat, sigmahat) (0 if s
%         lies above the density grid)
% ksiqrsfrommode, |s - (mode of the kernel density)|/iqrsurr (NaN if iqrsurr = 0)
% normpatponmax, stdfrommean, ztestp, kspminfromext and ksphereonmax are NaN if the
% surrogates all have the same value.
% The output is NaN if tau cannot be determined; an error is raised if the statistic fails
% for all surrogates.

% ------------------------------------------------------------------------------
% Copyright (C) 2013-2026, Ben D. Fulcher <ben.d.fulcher@gmail.com>,
% <http://www.benfulcher.com>
%
% If you use this code for your research, please cite the following two papers:
%
% (1) B.D. Fulcher and N.S. Jones, "hctsa: A Computational Framework for Automated
% Time-Series Phenotyping Using Massive Feature Extraction, Cell Systems 5: 527 (2017).
% DOI: 10.1016/j.cels.2017.10.001
%
% (2) B.D. Fulcher, M.A. Little, N.S. Jones, "Highly comparative time-series
% analysis: the empirical structure of time series and their methods",
% J. Roy. Soc. Interface 10(83) 20130048 (2013).
% DOI: 10.1098/rsif.2013.0048
%
% This function is free software: you can redistribute it and/or modify it under
% the terms of the GNU General Public License as published by the Free Software
% Foundation, either version 3 of the License, or (at your option) any later
% version.
%
% This program is distributed in the hope that it will be useful, but WITHOUT
% ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
% FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
% details.
%
% You should have received a copy of the GNU General Public License along with
% this program. If not, see <http://www.gnu.org/licenses/>.
% ------------------------------------------------------------------------------

% ------------------------------------------------------------------------------
%% Check inputs, set defaults
% ------------------------------------------------------------------------------
% 1) time delay, TAU
if nargin < 2 || isempty(tau)
	tau = 1;
end
if strcmp(tau, 'ac')
	tau = CO_FirstCrossing(y, 'ac', 0, 'discrete');
elseif ischar(tau) && ismember(tau, {'ac1e', 'mi'})
	tau = BF_GetTau(y, tau); % adaptive delay, resolved once from the original series
end
if isnan(tau)
	out = NaN; return
end

% 2) number of surrogate data sets to generate, NSURR
if nargin < 3 || isempty(nsurr)
	nsurr = 50;
end

% 3) surrogate data method, SURRMETHOD
if nargin < 4 || isempty(surrMethod)
	fprintf(1, 'Surrogate method set to default: ''surrogate1''.\n');
	surrMethod = 1;
end
% surrMethod = 1: randomizes phases of fourier spectrum
% surrMethod = 2:  (see Theiler algorithm II)
% surrMethod = 3: permutes samples randomly

% 4) surrogate function, SURRFN
if nargin < 5 || isempty(surrfn)
	fprintf(1, 'surrogate function set to default value: ''tc3''.\n');
	surrfn = 'tc3';
end

% 5) randomSeed: how to treat the randomization
if nargin < 6
	randomSeed = []; % default for BF_ResetSeed
end

% ------------------------------------------------------------------------------
%% Do the calculation
% ------------------------------------------------------------------------------
% Statistic function, evaluated identically on the original series and on
% each surrogate (CO_TC3/CO_trev's out.raw is the same expression TSTOOL's
% own tc3/trev functions used):
switch surrfn
	case 'tc3'
		statFn = @(yy) CO_TC3(yy, tau);
	case 'trev'
		statFn = @(yy) CO_trev(yy, tau);
	otherwise
		error('Unknown surrogate function ''%s''', surrfn)
end

statY = statFn(y);
tc3_y = statY.raw;

% Map TSTOOL's numeric surrogate-method convention onto SD_MakeSurrogates:
switch surrMethod
	case 1 % randomizes phases of fourier spectrum
		nativeSurrMethod = 'RP';
	case 2 % Theiler's algorithm II
		nativeSurrMethod = 'AAFT';
	case 3 % permutes samples randomly
		nativeSurrMethod = 'RandPerm';
	otherwise
		error('Unknown surrogate method %d', surrMethod)
end

% Generate surrogates (SD_MakeSurrogates resets the random seed itself) and
% evaluate the same statistic on each:
surrogates = SD_MakeSurrogates(y, nativeSurrMethod, nsurr, [], randomSeed);
tc3_surr = zeros(nsurr, 1);
num_surr = zeros(nsurr, 1); % the statistic's numerator on each surrogate
for i = 1:nsurr
	statSurr = statFn(surrogates(:, i));
	tc3_surr(i) = statSurr.raw;
	num_surr(i) = statSurr.num;
end

if all(isnan(tc3_surr))
	error('Surrogate statistic ''%s'' failed for all surrogates', surrfn);
end

% figure; histogram(tc3_surr);

% ------------------------------------------------------------------------------
%% Get some outputs
% ------------------------------------------------------------------------------
% These are completely from my intuition

% 1) fit a Gaussian to surrogates
% [muhat,sigmahat] = normfit(tc3_surr);
muhat = mean(tc3_surr);
sigmahat = std(tc3_surr);

if sigmahat == 0
	% All surrogates give an identical value of this statistic: cannot
	% meaningfully assess how many stds/z the data value is from them.
	out.normpatponmax = NaN;
	out.stdfrommean = NaN;
	out.ztestp = NaN;
else
	% probability of data given Guassian surrogates
	out.normpatponmax = normpdf(tc3_y, muhat, sigmahat) / normpdf(muhat, muhat, sigmahat);

	% Probability at least that distance from mean, using ztest:

	% 2) stds from mean
	out.stdfrommean = abs(tc3_y - mean(tc3_surr)) / sigmahat;
	% (~equivalent to a z-test:)
	[~, out.ztestp] = ztest(tc3_y, muhat, sigmahat);
	% (both of these stats are a monotonic function of normpatponmax)
end

% signed z-score (NaN if the surrogates' spread is at rounding level)
if sigmahat <= 1e-10 * max(abs(tc3_surr))
	out.zsigned = NaN;
else
	out.zsigned = (tc3_y - muhat) / sigmahat;
end

% iqrs from median
iqrsurr = iqr(tc3_surr);
if iqrsurr == 0
	out.iqrsfrommedian = NaN;
else
	out.iqrsfrommedian = abs(tc3_y - median(tc3_surr)) / iqrsurr;
end

% 3) basic info on surrogates
out.stdsurr = sigmahat;
out.meansurr = muhat;
out.meannumsurr = mean(num_surr);

% 4) kernel density test
[ksf, ksx] = BF_KSDensity(tc3_surr);
% hold on;plot(ksx,ksf,'r')
if any(isnan(ksf)) % all surrogates have the same value: no scale to smooth over
	out.kspminfromext = NaN;
	out.ksphereonmax = NaN;
else
	ksdx = ksx(2) - ksx(1);
	ihit = find(ksx > tc3_y, 1, 'first');

	if isempty(ihit) %% off the scale!
		out.kspminfromext = 0;
		out.ksphereonmax = 0;
	else % on the scale!
		pfromleft = ksdx * sum(ksf(1:ihit));
		% pfromright = ksdx*sum(ksf(ihit+1:end))
		out.kspminfromext = min([pfromleft 1 - pfromleft]);
		% out.phereonstd = ksf(ihit)/sigmahat;
		out.ksphereonmax = ksf(ihit) / normpdf(muhat, muhat, sigmahat);
		%     out.ksiqrsfrommode = abs(ksx(imode)-ksx(ihit))/iqr(tc3_surr);
	end
end

% iqrs from mode
imode = find(ksf == max(ksf), 1, 'first');
if iqrsurr == 0
	out.ksiqrsfrommode = NaN;
else
	out.ksiqrsfrommode = abs(ksx(imode) - tc3_y) / iqrsurr;
end

end
