function ImportDataString = SQL_ImportDataString(whattable)
% Determines the appropriate mySQL IMPORT DATA statement to use to import the approriate .csv file in the given mysql table
% Ben Fulcher, June 2013

switch whattable
case 'TimeSeriesDistributionCodes'
    % Import time series distribution codes from INP_dcodes.csv into the TimeSeriesDistributionCodes Table
    ImportDataString = ['LOAD DATA LOCAL INFILE ''INP_dcodes.csv'' INTO TABLE TimeSeriesDistributionCodes ' ...
        'FIELDS TERMINATED BY '','' OPTIONALLY ENCLOSED BY ''"'' ESCAPED BY ''"'' LINES TERMINATED BY ''\r'' ' ...
        'IGNORE 1 LINES ' ...
        '(Dcode_id, Description);'];

case 'TimeSeriesSource'
    % Import source information from INP_sources.csv into the TimeSeriesSource table
    ImportDataString = ['LOAD DATA LOCAL INFILE ''INP_sources.csv'' INTO TABLE TimeSeriesSource ' ...
        'FIELDS TERMINATED BY '','' OPTIONALLY ENCLOSED BY ''"'' ESCAPED BY ''"'' LINES TERMINATED BY ''\r''' ...
        'IGNORE 1 LINES ' ...
        '(SourceName, Link, Description, ProcessingNote, AddedBy, Dcode_id, Parent);'];

case 'TimeSeriesCategories'
    % Import all category information from INP_categories.csv into the TimeSeriesCategories table
    ImportDataString = ['LOAD DATA LOCAL INFILE ''INP_categories.csv'' INTO TABLE TimeSeriesCategories ' ...
        'FIELDS TERMINATED BY '','' OPTIONALLY ENCLOSED BY ''"'' ESCAPED BY ''"'' LINES TERMINATED BY ''\r'' ' ...
        'IGNORE 1 LINES ' ...
        '(CategoryName, Description, ParentString);'];

case 'TimeSeries'
    % Import all time-series information from INP_ts.csv into the TimeSeries table
    ImportDataString = ['LOAD DATA LOCAL INFILE ''INP_ts.csv'' INTO TABLE TimeSeries ' ...
    'FIELDS TERMINATED BY '','' OPTIONALLY ENCLOSED BY ''"'' ESCAPED BY ''"'' LINES TERMINATED BY ''\r'' ' ...
    'IGNORE 1 LINES ' ...
    '(FileName, Keywords, Quantity, Unit, SamplingRate, Description, SourceString, CategoryString);'];

otherwise
    error(fprintf,1,'Unknown Table: %s',whattable)
end

end