function CreateString = SQL_TableCreateString(whattable)
% Determines the appropriate mySQL CREATE TABLE statement to use to create a given table, identified by the input string, whattable
% Ben Fulcher, May 2013

switch whattable
case 'Operations'
    CreateString = ['CREATE TABLE Operations ' ...
        '(m_id INTEGER NOT NULL AUTO_INCREMENT, ' ... % Unique integer identifier
        'OpName VARCHAR(255), ' ... % Unique name for the operation
        'Code VARCHAR(255), ' ... % Code to execute, or Master to retrieve from
        'Keywords VARCHAR(255), ' ... % Comma separated keyword metadata ...
        'MasterLabel VARCHAR(255), ' ... % Label of master code
        'Stochastic TINYINT(1), ' ... % Boolean identifier: is it a stochastic algorithm?
        'LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ' ... % Last modified
        'PRIMARY KEY (m_id))']; % sets primary key as m_id
        % 'Pointer TINYINT(1), ' ... % perhaps redundant given MasterLabel

case 'OperationCode'
    CreateString = ['CREATE TABLE OperationCode ' ...
        '(c_id INTEGER NOT NULL AUTO_INCREMENT, ' ...
        'CodeName VARCHAR(255), ' ...
        'Description TEXT, ' ...
        'LicenseType INTEGER UNSIGNED, ' ...
        'PRIMARY KEY (c_id))'];

case 'TimeSeries'
    CreateString = ['CREATE TABLE TimeSeries ' ...
        '(ts_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, ' ... % Unique integer identifier
        'Filename VARCHAR(255) NOT NULL, ' ... % FileName of the time series
        'Keywords VARCHAR(255), ' ... % Comma-delimited keywords assigned to the time series
        'Length INTEGER UNSIGNED, ' ... % Length of the time series
        'Data MEDIUMTEXT, ' ... % Add data into database :-O
        'LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)']; % Time stamp of when the time series was last modified/inserted
        % 'Quantity VARCHAR(255), ' ... % The quantity measured across time
        % 'Unit VARCHAR(50), ' ... % The physical unit of the quantity measured
        % 'SamplingRate VARCHAR(50), ' ... % Sampling rate of the time series
        % 'Description TEXT, ' ... % More information about this specific time series

case 'MasterOperations'
    CreateString = ['CREATE TABLE MasterOperations ' ...
        '(mop_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, ' ... % Unique integer identifier
        'MasterLabel VARCHAR(255), ' ... % Name given to master code file
        'MasterCode VARCHAR(255), ' ... % Code to execute
        'NPointTo INTEGER UNSIGNED, ' ... % Number of children
        'LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)']; % Time stamp of when entry was last modified
        
case 'MasterPointerRelate'
    CreateString = ['CREATE TABLE MasterPointerRelate ' ...
        '(mop_id INTEGER, ' ... % Unique integer identifier -- master operations
        'm_id INTEGER, ' ... % Unique integer identifier -- operations
        'FOREIGN KEY (m_id) REFERENCES Operations(m_id) ON DELETE CASCADE ON UPDATE CASCADE, ' ...
        'FOREIGN KEY (mop_id) REFERENCES MasterOperations(mop_id) ON DELETE CASCADE ON UPDATE CASCADE)'];
        
case 'OperationKeywords'
    CreateString = ['CREATE TABLE OperationKeywords ' ...
        '(mkw_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, ' ...
        'Keyword VARCHAR(255), ' ...
        'NumOccur INTEGER, ' ...
        'PercentageCalculated FLOAT, ' ...
        'PercentageGood FLOAT, ' ...
        'MeanCalcTime FLOAT)'];
        
case 'OpKeywordsRelate'
    CreateString = ['CREATE TABLE OpKeywordsRelate ' ...
        '(m_id INTEGER,' ...
        'mkw_id INTEGER, '  ...
        'FOREIGN KEY (mkw_id) REFERENCES OperationKeywords (mkw_id) ON DELETE CASCADE ON UPDATE CASCADE, ' ...
        'FOREIGN KEY (m_id) REFERENCES Operations (m_id) ON DELETE CASCADE ON UPDATE CASCADE)'];
        
case 'TimeSeriesKeywords'
    CreateString = ['CREATE TABLE TimeSeriesKeywords ' ...
        '(tskw_id INTEGER AUTO_INCREMENT PRIMARY KEY, ' ... % Unique identifier for each keyword
        'Keyword varchar(50), ' ... % The keyword
        'NumOccur INTEGER UNSIGNED, ' ... % Number of time series with this keyword
        'LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)'];
    
case 'TsKeywordsRelate'
    CreateString = ['CREATE TABLE TsKeywordsRelate ' ...
        '(ts_id INTEGER, ' ...
        'tskw_id INTEGER, ' ...
        'FOREIGN KEY (tskw_id) REFERENCES TimeSeriesKeywords(tskw_id) ON DELETE CASCADE ON UPDATE CASCADE, ' ...
        'FOREIGN KEY (ts_id) REFERENCES TimeSeries(ts_id) ON DELETE CASCADE ON UPDATE CASCADE)'];
    
case 'Results'
    CreateString = ['CREATE TABLE Results ' ...
        '(ts_id integer, ' ...
        'm_id INTEGER, ' ...
        'Output DOUBLE, ' ...
        'QualityCode INTEGER UNSIGNED, ' ...
        'CalculationTime FLOAT, ' ...
        'LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ' ...
        'FOREIGN KEY (ts_id) REFERENCES TimeSeries(ts_id) ON DELETE CASCADE ON UPDATE CASCADE, ' ...
        'FOREIGN KEY (m_id) REFERENCES Operations(m_id) ON DELETE CASCADE ON UPDATE CASCADE, '...
        'PRIMARY KEY(ts_id,m_id))'];

otherwise
    error(['Unknown table ' whattable]) 
end

end